### PR TITLE
Finished Validator

### PR DESCRIPTION
**Pull request by robinwei-itering**
1. Added 3 new markdown files and related screenshots;
2. Entries not inserted in the json file.

### CODE REVIEW

**Comment by robinwei-itering** [comment]
1. Added 4 modules in English and Chinese
    1.1 Need to choose ERC20 from centralized exchanges 
    1.2 Ethereum > Darwinia Transfer
    1.3 Darwinia > Ethereum Transfer
    1.4 How to Nominate
2.  Exclude How to Become a Nominator, because it is not for beginners
3.  JSON file not configured

**Comment by robinwei-itering** [comment]
1. Finished the text part of the Validator section;
2. Some screenshots need to be added by Aki;
3. The JSON configuration file needs to be modified.

**Comment by hackfisher** [comment]
@robinwei-itering ci failed.

**Comment by hackfisher** [comment]
@robinwei-itering For next pull requests, please checkout a branch in darwinia-network repo, and follow the naming convention, use your name as prefix. Refer https://github.com/darwinia-network/darwinia/blob/master/CONTRIBUTING.adoc#rules


Besides, I guess CI failed because it can not access `robinwei-itering:master`.

Please ACK above information, and I'll force merge this  later.

**Comment by robinwei-itering** [comment]
@HackFisher  I checked out a new branch in the base fork and will work on it in the future. Just reject this PR #174

**Comment by robinwei-itering** [comment]
Replaced by a new branch in the original repository

**Pull request closed without merging**
